apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hantbk/web_service.git'
    path: 'charts'
    targetRevision: HEAD
    helm:
      valueFiles:
        - 'https://raw.githubusercontent.com/hantbk/web_config/main/value.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps/v1
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
