apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hantbk/web_service.git'
    path: 'charts'
    helm:
      valueFiles:
        - 'https://raw.githubusercontent.com/hantbk/web_config/main/value.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncOptions:
        - CreateNamespace=true
      syncWave:
        phase: PreSync
        max: 1
      syncStrategy:
        automated:
          prune: true
          selfHeal: true
      syncInterval: 1m 
