name: Continuous Delivery Docker Image for API

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2
        id: buildx 

      - name: Extract metadata (tags, labels) for Web Image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/hant-web-service

      - name: Build and Push Docker Web Image
        uses: docker/build-push-action@v4
        id: docker_build_frontend
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: hantbk/web_config
          token: ${{ secrets.MY_REPO_TOKEN }}
          path: config-repo

      - name: List files in config repo
        run: ls -la config-repo

      - name: Check if values.yaml exists
        run: test -f config-repo/values.yaml && echo "values.yaml exists" || echo "values.yaml does not exist"

      - name: Print current values.yaml
        run: cat config-repo/values.yaml

      - name: Update Web image in values.yaml
        run: |
          cd config-repo
          sed -i "s|tag:.*|tag: \"${{ github.ref_name }}\"|g" values.yaml
          git config --global user.email "captainnemot1k60@gmail.com"
          git config --global user.name "hantbk"
          git add values.yaml
          git commit -m "Update API image to ${{ secrets.DOCKERHUB_USERNAME }}/hant-api-service:${{ github.ref_name }}"
          git push

      - name: Print updated values.yaml
        run: cat config-repo/values.yaml
